export enum EAppRouter {
  DASHBOARD = "/dashboard",
  BOOK_MANGEMENT_PAGE = "/book-management",
  BOOK_MANAGEMENT_DETAIL_PAGE = "/book-management/detail",
  BOOK_MANAGEMENT_ADD_PAGE = "/book-management/add",
  BOOK_MANAGEMENT_EDIT_PAGE = "/book-management/edit",
  AUTHOR_MANAGEMENT_PAGE = "/author-management",
  AUTHOR_MANAGEMENT_ADD_PAGE = "/author-management/add",
  AUTHOR_MANAGEMENT_EDIT_PAGE = "/author-management/edit",
  BORROWING_MANAGEMENT_PAGE = "/borrowing-management",
  BORROWING_MANAGEMENT_ADD_PAGE = "/borrowing-management/add",
  BORROWING_MANAGEMENT_EDIT_PAGE = "/borrowing-management/edit",
  GENRE_MANGEMENT_PAGE = "/genre-management",
  GENRE_MANGEMENT_ADD_PAGE = "/genre-management/add",
  GENRE_MANGEMENT_EDIT_PAGE = "/genre-management/edit",
}
