export enum MEMBER_TYPE {
  LECTURER = "LECTURER",
  UNDERGRADUATE_STUDENT = "UNDERGRADUATE_STUDENT",
  GRADUATED_STUDENT = "GRADUATED_STUDENT",
  POSTGRADUATE_STUDENT = "POSTGRADUATE_STUDENT",
  LIBRARY_STAFF = "LIBRARY_STAFF",
  GUEST_READER = "GUEST_READER",
}

export const MEMBER_TYPE_DISPLAY = {
  [MEMBER_TYPE.LECTURER]: "Giảng viên",
  [MEMBER_TYPE.UNDERGRADUATE_STUDENT]: "Sinh viên đang theo học",
  [MEMBER_TYPE.GRADUATED_STUDENT]: "Sinh viên đã tốt nghiệp",
  [MEMBER_TYPE.POSTGRADUATE_STUDENT]: "Sinh viên cao học",
  [MEMBER_TYPE.LIBRARY_STAFF]: "Nhân viên thư viện",
  [MEMBER_TYPE.GUEST_READER]: "Khách",
};
