import { Toaster } from "sonner";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { AppSidebar } from "@/common/app-sidebar";
import { SidebarProvider } from "@/ui/sidebar";
import { NextFontWithVariable } from "next/dist/compiled/@next/font";
import "@/assets/css/globals.css";

const geistSans: NextFontWithVariable = localFont({
  src: "../assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono: NextFontWithVariable = localFont({
  src: "../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Library Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="vn">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <AppSidebar />
          <Toaster position="top-right" />
          <main className="w-full p-4">{children}</main>
        </SidebarProvider>
      </body>
    </html>
  );
}
